// Generated by LiveScript 1.5.0
(function(){
  var wp, main;
  wp = new WeakMap();
  main = function(Fn){
    var Maybe, A;
    Maybe = wp.get(Fn);
    if (Maybe) {
      return Maybe;
    } else {
      A = function(x){
        return Fn(x);
      };
      return wp.set(Fn, A);
    }
  };
  module['export'] = main;
}).call(this);
