// Generated by LiveScript 1.5.0
(function(){
  var genLargeNestedList, list, most, apply, ref$, diff, mem, start, Tstart, out;
  global.gc();
  genLargeNestedList = function(outer, inner){
    var list, i$, I, nest, j$, K;
    list = [];
    for (i$ = 1; i$ <= outer; ++i$) {
      I = i$;
      nest = [];
      for (j$ = 1; j$ <= inner; ++j$) {
        K = j$;
        nest.push(Math.round(Math.random() * 100));
      }
      list.push(nest);
    }
    return list;
  };
  list = genLargeNestedList(100, 2);
  most = require("most");
  apply = require("./main");
  ref$ = require("./mem"), diff = ref$.diff, mem = ref$.mem;
  start = mem();
  Tstart = new Date().getTime();
  out = most.from(list).chain(function(x){
    return most.from(x);
  }).reduce(function(accum, x){
    accum.push(x);
    return accum;
  }, []);
  out.then(function(full){
    var final, Tfinal;
    final = mem();
    Tfinal = new Date().getTime();
    console.log(diff(start, final));
    return console.log("Time :" + (Tfinal - Tstart));
  });
}).call(this);
